### ISSUE TITLE
UI set up 

### ISSUE THREAD

**Issue by JuanchoDluffy** [nmsu-cs/project-swift-sorcerers#3]
Set up main dashboard that matches mockup

**Comment by austin-13** [comment]
Main dashboard now matches mockup.
<img width="974" alt="Screenshot 2024-04-20 at 11 15 41 AM" src="https://github.com/nmsu-cs/project-swift-sorcerers/assets/122950600/8e607e5b-1c6c-4e36-bf23-1225a3c551c0">
