### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by JuanchoDluffy** [nmsu-cs/project-swift-sorcerers#6]
Crete the simple landing page for the app

**Comment by austin-13** [comment]
Simple landing page done.
<img width="994" alt="Screenshot 2024-04-20 at 11 14 02 AM" src="https://github.com/nmsu-cs/project-swift-sorcerers/assets/122950600/16643afd-67d3-43e1-ad2e-a6a75bf1cc3f">
